config/routes.rb
Rails.application.routes.draw do
   
  

  scope module: :customers do
    #顧客トップページのルートパス
    root 'homes#top'
    #顧客の商品関連
    resources :products, only: [:index, :show]
    #カート内商品
    resources :cart_products, only: [:index, :create, :update, :destroy]
    delete 'cart_products' => 'cart_products#empty', as: :empty
    #顧客の注文関連
    post 'orders/confirm' => 'orders#confirm', as: :orders_confirm
    get 'orders/thanks' => 'orders#thanks', as: :orders_thanks
    resources :orders, only: [:index, :new, :create, :show]
    #顧客情報関連
    resource :customers, only: [:show, :edit, :update]
    get 'delete_account' => 'customers#delete_account', as: :delete_account
    patch 'delete_account' => 'customers#invalid', as: :invalid
    #顧客の配送先関連
    resources :destinations, except: [:new, :show]
  end

  namespace :admins do
    root 'homes#top'
    resources :products, only: [:index,:new,:create,:show,:edit,:update]
    resources :genres, only: [:index,:create,:edit,:update]
    resources :customers, only: [:index,:show,:edit,:update]
    resources :orders, only: [:index,:show,:update]
    resources :order_products, only: [:update]
  end
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
  registrations: 'customers/registrations'
  }

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  
  get 'search' => 'search#search', as: :search

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_paranoid

  has_many :orders, dependent: :destroy
  has_many :cart_products, dependent: :destroy
  has_many :products, through: :cart_products
  has_many :destinations, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_products, dependent: :destroy
    has_many :products, through: :order_products

    belongs_to :customer

    enum payment: {'クレジットカード': 0, '銀行振込': 1}
    enum status: {wait:0, confirm:1, production:2, preparation: 3, complete: 4}
    # STATUS = {'入金待ち': 0, '入金確認': 1, '製作中': 2, '発送準備中': 3, '発送済み': 4}

    def total_quantity
    	orderProducts = order_products.all
    	total_quantity = 0
    	orderProducts.each do |order_product|
    		total_quantity += order_product.quantity
    	end
    	return total_quantity
    end
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.with_deleted.all
  end

  def show
    @customer = Customer.with_deleted.find(params[:id])
  end

  def edit
    @customer = Customer.with_deleted.find(params[:id])
  end

  def update
    customer = Customer.with_deleted.find(params[:id])
    Customer.update(customer_params)
    redirect_to admins_customer_path(customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:family_name, :first_name, :family_name_ruby, :first_name_ruby, :postcode, :address, :tell_number, :email)
  end

end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products.all
  end

  # 制作ステータス
  def update
    order = Order.find(params[:id])
    order.status = params[:order][:status].to_i
    order.update(update_params)
    redirect_to admins_order_path(order)
  end

  private
    def update_params
        params.require(:order).permit(:status)
    end
end

app/controllers/customers/cart_products_controller.rb
class Customers::CartProductsController < ApplicationController
	before_action :authenticate_customer!

	def index
		@cart_products = CartProduct.where(customer_id: current_customer.id)
	end

	def create
		cart_product = current_customer.cart_products.new(cart_product_params)
		cart_product.product_id = params[:product_id]
		cart_product.save
		redirect_to cart_products_path
	end

	def update
		@cart_product = CartProduct.find(params[:id])
		@cart_product.update(cart_product_params)
		redirect_to cart_products_path
	end

	def destroy
		@cart_product = CartProduct.find(params[:id])
		@cart_product.destroy
		redirect_to cart_products_path
	end

	def empty
		cart_products = CartProduct.where(customer_id: current_customer.id)
		cart_products.destroy_all
		redirect_to cart_products_path
		# render :index
	end

	private

		def cart_product_params
			params.require(:cart_product).permit(:quantity)
		end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
    before_action :authenticate_customer!

    def show
        @customer = Customer.find_by(id: current_customer.id)
    end

    def delete_account
    end

    def invalid
        customer = Customer.find_by(id: current_customer.id)
        if customer.destroy
            customer.update(is_valid: false)
        end
        redirect_to root_path
    end

    def edit
        @customer = Customer.find_by(id: current_customer.id)
    end

    def update
        customer = Customer.find_by(id: current_customer.id)
        customer.update(customer_params)
        redirect_to customers_path(customer.id)
    end

    private
    def customer_params
        params.require(:customer).permit(:family_name, :first_name, :family_name_ruby, :first_name_ruby, :email, :postcode, :address, :tell_number, :is_valid)
    end
end

app/controllers/customers/destinations_controller.rb
class Customers::DestinationsController < ApplicationController
	before_action :authenticate_customer!

	def index
		@destinations = Destination.where(customer_id: current_customer.id)
		@destination = current_customer.destinations.new
	end

    def create
    	@destination = current_customer.destinations.new(destination_params)
    	if @destination.save
    	    redirect_to destinations_path
    	else
    		redirect_to root_path
    	end
    end

	def edit
		@destination = Destination.find(params[:id])
	end

	def update
		@destination = Destination.find(params[:id])
		if @destination.update(destination_params)
		redirect_to destinations_path
	    else
	    redirect_to root_path
		end
	end

	def destroy
		destination = Destination.find(params[:id])
		destination.destroy
		redirect_to destinations_path
	end

	private

		def destination_params
			params.require(:destination).permit(:postcode, :address, :name)
		end

end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController
	def top
		@products = Product.all
	end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
    before_action :authenticate_customer!

    def index
        @orders = current_customer.orders.all
    end

    def new
        # 支払い方法入力するため記載
        @order = Order.new
    end

    def confirm
        # 注文商品を全て表示するために記載
        @orders = current_customer.cart_products.all
        @order = Order.new(order_params)
        if params[:select_radio] == "1"
            @order.shipping_postcode = current_customer.postcode
            @order.shipping_address = current_customer.address
            @order.shipping_name = current_customer.family_name + current_customer.first_name
            @order.payment = params[:order][:payment]
        elsif params[:select_radio] == "2"
            @destination = Destination.find(params[:order][:select_destinations])
            @order.shipping_postcode = @destination.postcode
            @order.shipping_address = @destination.address
            @order.shipping_name = @destination.name
            @order.payment = params[:order][:payment]
        elsif params[:select_radio] == "3"
            @order.shipping_postcode = params[:order][:shipping_postcode]
            @order.shipping_address = params[:order][:shipping_address]
            @order.shipping_name = params[:order][:shipping_name]
            @order.payment = params[:order][:payment]
        end
    end

    def create
        #既に登録済みのデータと新規入力情報
        @order = current_customer.orders.new(order_params)
        cart_products = current_customer.cart_products.all
        if @order.save
            destination = current_customer.destinations.new(destination_params)
            destination.postcode = params[:order][:shipping_postcode]
            destination.address = params[:order][:shipping_address]
            destination.name = params[:order][:shipping_name]
            destination.save
            cart_products.each do |cart_product|
                order_product = OrderProduct.new(order_products_params)
                order_product.product_id = cart_product.product_id
                order_product.order_id = @order.id
                order_product.quantity = cart_product.quantity
                product = Product.find(cart_product.product_id)
                order_product.price = product.price
                order_product.save
            end
            cart_products.destroy_all
            redirect_to orders_thanks_path
        end
    end

    def thanks
    end

    def show
        @order = Order.find(params[:id])
        @order_products = OrderProduct.where(order_id: @order.id)
    end

    private

    def order_params
    params.require(:order).permit(:total_price, :status, :shipping_name, :shipping_postcode, :shipping_address, :payment)
    end

    def order_products_params
        params.require(:order).permit(:quantity, :price)
    end

    def destination_params
        params.require(:destination).permit(:postcode, :address, :name)
    end

end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/products_controller.rb
class Customers::ProductsController < ApplicationController
	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
		if customer_signed_in?
			@quantity = current_customer.cart_products.new
		end
	end

end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customers/cart_products_helper.rb
module Customers::CartProductsHelper
end

app/views/customers/orders/confirm.html.erb
<h1>注文確認画面</h1>
<div class="row">
    <div class="col-xs-8">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>商品名</th>
                    <th>単価（税込）</th>
                    <th>数量</th>
                    <th>小計</th>
                </tr>
            </thead>
            <tbody>
            <% total_price = 0 %>
            <% @orders.each do |order| %>
                <tr>
                    <td><%= order.product.name %></td>
                    <td><%= order.product.price %></td>
                    <td><%= order.quantity %></td>
                    <td>
                        <%= order.subtotal_price %>
                        <% total_price += order.subtotal_price %>
                    </td>
                </tr>
            <% end %>
            </tbody>
        </table>
    </div>


    <div class="col-xs-4">
        <table class="table table-bordered">
                <tr>
                    <th>送料</th>
                    <td>800</td>
                </tr>
                <tr>
                    <th>商品合計</th>
                    <td><%= total_price %></td>
                </tr>
                <tr>
                    <th>請求金額</th>
                    <td>
                        <% billing_amount = total_price + 800 %>
                        <%= billing_amount %>
                    </td>
                </tr>
        </table>
    </div>
</div>

<div class="order_confirm">

    <span>支払方法</span><%= @order.payment %>
    <span>お届け先</span><%= @order.shipping_address %>
    <%= form_with model: @order, url: orders_path , local: true do |f| %>
        <%= f.hidden_field :shipping_name, :value => @order.shipping_name %>
        <%= hidden_field_tag 'destination[name]', :value => @order.shipping_name %>
        <%= f.hidden_field :shipping_postcode, :value => @order.shipping_postcode %>
        <%= hidden_field_tag 'destination[postcode]', :value => @order.shipping_postcode %>
        <%= f.hidden_field :shipping_address, :value => @order.shipping_address %>
        <%= hidden_field_tag 'dstination[address]', :value => @order.shipping_address %>
        <%= f.hidden_field :payment, :value => @order.payment %>
        <%= f.hidden_field :total_price, :value => billing_amount %>


    <%= f.submit "詳細入力へ戻る", name: "back" %>
    <%= f.submit "注文を確定する" %>
    <% end %>
</div>

app/views/customers/orders/index.html.erb
<h2>注文履歴一覧</h2>
<table class="table table-bordered">
	<thead>
		<tr>
			<th>注文日</th>
			<th>配送先</th>
			<th>注文商品</th>
			<th>支払い金額</th>
			<th>ステータス</th>
			<th>注文詳細</th>
		</tr>
	</thead>
	<tbody>
		<% @orders.each do |order| %>
		<tr>
			<td><%= order.created_at.strftime("%Y/%m/%d %H:%M") %></td>
			<td>
				<%= order.shipping_postcode %></br>
				<%= order.shipping_address %></br>
				<%= order.shipping_name %>
			</td>
			<td>
				<% order.order_products.each do |order_product| %>
				<%= order_product.product.name %></br>
				<% end %>
			</td>
			<td><%= order.payment %></td>
			<td><%= order.status_i18n %></td>
			<td><%= link_to '表示する', order_path(order.id) %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/customers/orders/new.html.erb
<h1>注文情報入力</h1>
<%= form_with model: @order, url: orders_confirm_path, local: true do |f| %> 
<div class="pay">
    <h2>支払方法</h2>
    <%= f.radio_button :payment, "クレジットカード" %>
    <%= f.label :payment, "クレジットカード", {style: "display: inline-block;"} %><br>
    <%= f.radio_button :payment, "銀行振込" %>
    <%= f.label :payment, "銀行振込", {style: "display: inline-block;"} %>
</div>
<div class="shipping">
    <h2>お届け先</h2>

    <%= radio_button_tag(:select_radio, 1) %>
    <%= current_customer.address %><br>
    
    <%= radio_button_tag(:select_radio, 2) %>
    <%= f.label :shipping_address, "既に登録済み", {style: "display: inline-block;"} %>
    <%= f.select :select_destinations, current_customer.destinations.all.map{|destination| [destination.address, destination.id]}, {style: "display: block;"} %><br>
    
    <%= radio_button_tag(:select_radio, 3) %>
    <%= f.label :shipping_address, "新しいお届け先", {style: "display: inline-block;"} %><br>
    <%= f.label :shipping_postcode, "郵便番号（ハイフンなし）", {style: "display: inline-block;"} %>
    <%= f.text_field :shipping_postcode %><br>
    <%= f.label :shipping_address, "住所", {style: "display: inline-block;"} %>
    <%= f.text_field :shipping_address %><br>
    <%= f.label :shipping_name, "宛名", {style: "display: inline-block;"} %>
    <%= f.text_field :shipping_name %><br>

</div>

<%= f.submit "確認画面へ", class: "btn btn-primary" %>

<% end %>

app/views/customers/orders/show.html.erb
<div class="row">
	<div class="col-xs-7">
		<h4>注文情報</h4>
		<table class="table table-bordered">
				<tr>
					<th>注文日</th>
					<td><%= @order.created_at.strftime("%Y/%m/%d %H:%M") %></td>
				</tr>
				<tr>
					<th>配送先</th>
					<td>
						<%= @order.shipping_postcode %></br>
						<%= @order.shipping_address %></br>
						<%= @order.shipping_name %>
					</td>
				</tr>
				<tr>
					<th>支払い方法</th>
					<td><%= @order.payment %></td>
				</tr>
				<tr>
					<th>ステータス</th>
					<td><%= @order.status_i18n %></td>
				</tr>
		</table>
	</div>
	<div class="col-xs-4">
		<h4>請求情報</h4>
		<table class="table table-bordered">
				<tr>
					<th>商品合計</th>
					<% total_product_price = 0 %>
					<% @order_products.each do |order_product| %>
					<% total_product_price += order_product.subtotal_price %>
					<% end %>
					<td><%= total_product_price %></td>
				</tr>
				<tr>
					<th>配送料</th>
					<td><%= @order.shippings %></td>
				</tr>
				<tr>
					<th>請求金額</th>
					<td><%= @order.total_price %></td>
				</tr>
		</table>
	</div>
</div>
	<div class="row">
		<div class="col-xs-8">
			<h4>注文内容</h4>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>商品</th>
						<th>単価（税込）</th>
						<th>個数</th>
						<th>小計</th>
					</tr>
				</thead>
				<tbody>
					<% @order_products.each do |order_product| %>
					<tr>
						<td><%= order_product.product.name %></td>
						<td><%= order_product.tax_price.floor %></td>
						<td><%= order_product.quantity %></td>
						<td><%= order_product.subtotal_price %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/customers/orders/thanks.html.erb
<h1>ご注文ありがとうございました</h1>