config/routes.rb
Rails.application.routes.draw do
   
  

  scope module: :customers do
    #顧客トップページのルートパス
    root 'homes#top'
    #顧客の商品関連
    resources :products, only: [:index, :show]
    #カート内商品
    resources :cart_products, only: [:index, :create, :update, :destroy]
    delete 'cart_products' => 'cart_products#empty', as: :empty
    #顧客の注文関連
    post 'orders/confirm' => 'orders#confirm', as: :orders_confirm
    get 'orders/thanks' => 'orders#thanks', as: :orders_thanks
    resources :orders, only: [:index, :new, :create, :show]
    #顧客情報関連
    resource :customers, only: [:show, :edit, :update]
    get 'delete_account' => 'customers#delete_account', as: :delete_account
    patch 'delete_account' => 'customers#invalid', as: :invalid
    #顧客の配送先関連
    resources :destinations, except: [:new, :show]
  end

  namespace :admins do
    root 'homes#top'
    resources :products, only: [:index,:new,:create,:show,:edit,:update]
    resources :genres, only: [:index,:create,:edit,:update]
    resources :customers, only: [:index,:show,:edit,:update]
    resources :orders, only: [:index,:show,:update]
    resources :order_products, only: [:update]
  end
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
  registrations: 'customers/registrations'
  }

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  
  get 'search' => 'search#search', as: :search

end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_products, dependent: :destroy
    has_many :products, through: :order_products

    belongs_to :customer

    enum payment: {'クレジットカード': 0, '銀行振込': 1}
    enum status: {wait:0, confirm:1, production:2, preparation: 3, complete: 4}
    # STATUS = {'入金待ち': 0, '入金確認': 1, '製作中': 2, '発送準備中': 3, '発送済み': 4}

    def total_quantity
    	orderProducts = order_products.all
    	total_quantity = 0
    	orderProducts.each do |order_product|
    		total_quantity += order_product.quantity
    	end
    	return total_quantity
    end
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products.all
  end

  # 制作ステータス
  def update
    order = Order.find(params[:id])
    order.status = params[:order][:status].to_i
    order.update(update_params)
    redirect_to admins_order_path(order)
  end

  private
    def update_params
        params.require(:order).permit(:status)
    end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
    before_action :authenticate_customer!

    def index
        @orders = current_customer.orders.all
    end

    def new
        # 支払い方法入力するため記載
        @order = Order.new
    end

    def confirm
        # 注文商品を全て表示するために記載
        @orders = current_customer.cart_products.all
        @order = Order.new(order_params)
        if params[:select_radio] == "1"
            @order.shipping_postcode = current_customer.postcode
            @order.shipping_address = current_customer.address
            @order.shipping_name = current_customer.family_name + current_customer.first_name
            @order.payment = params[:order][:payment]
        elsif params[:select_radio] == "2"
            @destination = Destination.find(params[:order][:select_destinations])
            @order.shipping_postcode = @destination.postcode
            @order.shipping_address = @destination.address
            @order.shipping_name = @destination.name
            @order.payment = params[:order][:payment]
        elsif params[:select_radio] == "3"
            @order.shipping_postcode = params[:order][:shipping_postcode]
            @order.shipping_address = params[:order][:shipping_address]
            @order.shipping_name = params[:order][:shipping_name]
            @order.payment = params[:order][:payment]
        end
    end

    def create
        #既に登録済みのデータと新規入力情報
        @order = current_customer.orders.new(order_params)
        cart_products = current_customer.cart_products.all
        if @order.save
            destination = current_customer.destinations.new(destination_params)
            destination.postcode = params[:order][:shipping_postcode]
            destination.address = params[:order][:shipping_address]
            destination.name = params[:order][:shipping_name]
            destination.save
            cart_products.each do |cart_product|
                order_product = OrderProduct.new(order_products_params)
                order_product.product_id = cart_product.product_id
                order_product.order_id = @order.id
                order_product.quantity = cart_product.quantity
                product = Product.find(cart_product.product_id)
                order_product.price = product.price
                order_product.save
            end
            cart_products.destroy_all
            redirect_to orders_thanks_path
        end
    end

    def thanks
    end

    def show
        @order = Order.find(params[:id])
        @order_products = OrderProduct.where(order_id: @order.id)
    end

    private

    def order_params
    params.require(:order).permit(:total_price, :status, :shipping_name, :shipping_postcode, :shipping_address, :payment)
    end

    def order_products_params
        params.require(:order).permit(:quantity, :price)
    end

    def destination_params
        params.require(:destination).permit(:postcode, :address, :name)
    end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customers/orders_helper.rb
module Customers::OrdersHelper
end

app/views/admins/orders/index.html.erb
<h1>注文履歴一覧</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
        </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
        <tr>
            <td><%= link_to order.created_at.strftime("%Y/%m/%d %H:%M:%S"), admins_order_path(order.id) %></td>
            <td><%= "#{order.customer.family_name}　#{order.customer.first_name}" %></td>
            <td><%= order.total_quantity %></td>
            <td><%= order.status_i18n %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/admins/orders/show.html.erb
<h1>注文履歴詳細</h1>
<div class = "show">
<p>購入者</p>
<%= link_to "#{@order.customer.family_name} #{@order.customer.first_name}", admins_customer_path(@order.customer_id) %>
<p>配送先</p>
<%= "#{@order.shipping_postcode} #{@order.shipping_address} " %>
<%= @order.shipping_name %>
<p>支払い方法</p>
<%= @order.payment %>
<p>注文ステータス</p>
<%= form_with model: @order, url: admins_order_path(@order.id), method: :patch, local: true do |f| %>
    <%= f.select :status, Order.statuses_i18n.invert %>
    <%= f.submit "更新", class: "btn btn-primary" %>
<% end %>
</div>

<table class = "index table table-bordered">
<thead>
    <tr>
        <th>商品名</th>
        <th>単価（税込）</th>
        <th>数量</th>
        <th>小計</th>
        <th>製作ステータス</th>
    </tr>
</thead>
<tbody>
<% @order_products.each do |order_product| %>
    <tr>
        <td><%= order_product.product.name %></td>
        <td><%= order_product.tax_price %></td>
        <td><%= order_product.quantity %></td>
        <td><%= order_product.subtotal_price %></td>
        <td>
        <%= form_with model: order_product, url: admins_order_product_path(order_product.id), local: true do |f| %>
            <%= f.select :status, OrderProduct.statuses_i18n.invert %>
            <%= f.submit "更新", class: "btn btn-primary" %>
        <% end %>
        </td>
        <% end %>
    </tr>
</tbody>

</table>